import React, { useState } from 'react'
import { Campaign } from '../types'

interface Props {
  open: boolean
  loading: boolean
  campaign: Campaign | null
  onClose: () => void
  onRegenerate: () => void
}

const CampaignPreview: React.FC<Props> = ({
  open,
  loading,
  campaign,
  onClose,
  onRegenerate,
}) => {
  const [tab, setTab] = useState<'email' | 'sms'>('email')
  const [copied, setCopied] = useState('')

  const copy = (text: string, which: string) => {
    navigator.clipboard?.writeText(text)
    setCopied(which)
    setTimeout(() => setCopied(''), 1500)
  }

  const wordCount = campaign ? campaign.email_body.trim().split(/\s+/).length : 0
  const smsLen = campaign ? campaign.sms_body.length : 0

  return (
    <>
      <div className={`drawer-overlay ${open ? 'open' : ''}`} onClick={onClose} />
      <aside className={`drawer ${open ? 'open' : ''}`}>
        <div className="drawer-head">
          <div>
            <div style={{ fontWeight: 700, fontSize: 16, textTransform: 'capitalize' }}>
              {campaign ? campaign.segment.replace(/_/g, ' ') : 'Campaign'} Campaign
            </div>
            {campaign && (
              <div className="muted">
                {campaign.source === 'claude'
                  ? 'Generated by Claude'
                  : campaign.source === 'database'
                  ? 'Pre-generated copy from demo database'
                  : 'Templated preview (no API key set)'}
              </div>
            )}
          </div>
          <button className="close-x" onClick={onClose}>
            &times;
          </button>
        </div>

        <div className="drawer-body">
          {loading && (
            <div>
              <div className="spinner" />
              <p className="muted" style={{ textAlign: 'center' }}>
                Claude is writing your campaign…
              </p>
            </div>
          )}

          {!loading && campaign && (
            <>
              <div className="tabs">
                <button
                  className={`tab ${tab === 'email' ? 'active' : ''}`}
                  onClick={() => setTab('email')}
                >
                  Email Preview
                </button>
                <button
                  className={`tab ${tab === 'sms' ? 'active' : ''}`}
                  onClick={() => setTab('sms')}
                >
                  SMS Preview
                </button>
              </div>

              {tab === 'email' && (
                <div>
                  <div className="email-frame">
                    <div className="subj">{campaign.subject_line}</div>
                    <div className="body">{campaign.email_body}</div>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 12 }}>
                    <span className="badge amber mono">{wordCount} words</span>
                    <button
                      className="btn-secondary"
                      onClick={() =>
                        copy(`${campaign.subject_line}\n\n${campaign.email_body}`, 'email')
                      }
                    >
                      {copied === 'email' ? 'Copied!' : 'Copy to Clipboard'}
                    </button>
                  </div>
                </div>
              )}

              {tab === 'sms' && (
                <div>
                  <div className="phone">
                    <div className="notch" />
                    <div className="sms-bubble">{campaign.sms_body}</div>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 12 }}>
                    <span className={`count-badge mono ${smsLen > 160 ? 'over' : ''}`}>
                      {smsLen} / 160
                    </span>
                    <button className="btn-secondary" onClick={() => copy(campaign.sms_body, 'sms')}>
                      {copied === 'sms' ? 'Copied!' : 'Copy'}
                    </button>
                  </div>
                </div>
              )}
            </>
          )}
        </div>

        {campaign && !loading && (
          <div className="drawer-foot">
            <div style={{ textAlign: 'center' }}>
              <div className="muted">Send Estimate</div>
              <div className="mono" style={{ fontWeight: 700 }}>
                {campaign.send_estimate.toLocaleString()}
              </div>
            </div>
            <div style={{ textAlign: 'center' }}>
              <div className="muted">Open Rate</div>
              <div className="mono" style={{ fontWeight: 700, color: 'var(--amber)' }}>
                {Math.round(campaign.projected_open_rate * 100)}%
              </div>
            </div>
            <div style={{ textAlign: 'center' }}>
              <div className="muted">Segment</div>
              <div className="mono" style={{ fontWeight: 700 }}>
                {campaign.fan_count.toLocaleString()}
              </div>
            </div>
            <button className="btn-primary" onClick={onRegenerate}>
              Regenerate
            </button>
          </div>
        )}
      </aside>
    </>
  )
}

export default CampaignPreview
